server:
  port: 8080

spring:
  application:
    name: Customer
  datasource:
    username: houssam
    url: jdbc:postgresql://localhost:1234/customer
    password: houssam
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'