server:
  port: 8083

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers(?<segment>/?.*), /api/v1/customers${segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: false
      register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0