server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: houssam
    url: jdbc:postgresql://localhost:1234/fraud
    password: houssam
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: false
      register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0